# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "exclude"
    commit-message:
      prefix: "chore(github-actions)"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      #interval: "daily"
      #interval: "monthly"
      interval: "weekly"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore(cargo)"
    reviewers:
      - "phial3"
    assignees:
      - "phial3"
    target-branch: "rsmpeg"
    open-pull-requests-limit: 5
    groups:
      rust:
        patterns:
          - "*"
