[package]
name = "rsmedia"
version = "0.1.0"
edition = "2021"
build = "build.rs"
readme = "README.md"
license = "MIT OR Apache-2.0"
description = "High-level video toolkit based on ffmpeg."
keywords = ["video", "ffmpeg", "encoding", "decoding", "muxing"]
categories = ["multimedia", "multimedia::video", "multimedia::audio"]
authors = ["Oddity.ai Developers <hello@oddity.ai>", "phial3 Developers"]
repository = "https://github.com/phial3/rsmedia.git"
exclude = [".github/*", "assets/*", "data/*", "examples/*", "tests/*", "benches/*", "docs/*", ]

[features]
default = ["ndarray", "ffmpeg7", "link_system_ffmpeg"]
ffmpeg6 = ["rsmpeg/ffmpeg6"]
ffmpeg7 = ["rsmpeg/ffmpeg7"]
## unxi linking ffmpeg with pkg-config.
link_system_ffmpeg = ["rsmpeg/link_system_ffmpeg", "pkg-config"]
## windows linking ffmpeg with vcpkg.
link_vcpkg_ffmpeg = ["rsmpeg/link_vcpkg_ffmpeg", "vcpkg"]

[dependencies]
url = "2.5"
dashmap = "6.1"
image = "0.25"
imageproc = "0.25"
num-traits = "0.2"
anyhow = "1.0"
log = "0.4"
tracing = "0.1"
once_cell = "1.21"
num_cpus = "1.16"
ndarray = { version = "0.16", optional = true }
yuvutils-rs = {version = "0.8", features = ["rayon", "professional_mode"]}
rsmpeg = { git = "https://github.com/phial3/rsmpeg", branch = "light", default-features = false }

[dev-dependencies]
libc = "0.2"
camino = "1.1"
chrono = "0.4"
ringbuf = "0.4"
ctor = "0.4"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter", "chrono"] }

## parallel
rayon = "1.10"

## security & async
futures = "0.3"
tokio = { version = "1", features = ["full"] }

## color
pix = "0.14"
palette = "0.7"
colorous = "1.0"
ab_glyph = "0.2"
libblur = "0.17"
pic-scale = "0.5"
colorutils-rs = "0.7"
histogram_equalization = "0.2"

## image & video
fast_image_resize = "=5.1"

## sound & audio
cpal = "0.15"
wavers = "1.5"
rubato = "0.16"
dasp = { version = "0.11", features = ["all"] }
rodio = { version = "0.20", features = ["symphonia-all", "tracing"] }

[build-dependencies]
vcpkg = { version = "0.2", optional = true }
pkg-config = { version = "0.3", optional = true }

[package.metadata.docs.rs]
all-features = true

[[example]]
name = "decode_frame"
path = "examples/decode_frame.rs"
required-features = ["ndarray"]

[[example]]
name = "encode_frame"
path = "examples/encode_frame.rs"
required-features = ["ndarray"]
