[package]
name = "rsmedia"
version = "0.1.0"
edition = "2021"
build = "build.rs"
readme = "README.md"
license = "MIT OR Apache-2.0"
description = "High-level video toolkit based on ffmpeg."
keywords = ["video", "ffmpeg", "encoding", "decoding", "muxing"]
categories = ["multimedia", "multimedia::video", "multimedia::audio"]
authors = ["phial3"]
repository = "https://github.com/dromara/rsmedia.git"
exclude = [".github/*", "assets/*", "data/*", "examples/*", "tests/*", "benches/*", "docs/*", ]

[features]
default = ["ndarray", "ffmpeg8", "link_system_ffmpeg"]
ffmpeg6 = ["rsmpeg/ffmpeg6"]
ffmpeg7 = ["rsmpeg/ffmpeg7_1"]
ffmpeg8 = ["rsmpeg/ffmpeg8"]
## unxi linking ffmpeg with pkg-config.
link_system_ffmpeg = ["rsmpeg/link_system_ffmpeg", "pkg-config"]
## windows linking ffmpeg with vcpkg.
link_vcpkg_ffmpeg = ["rsmpeg/link_vcpkg_ffmpeg", "vcpkg"]

[dependencies]
pix = "0.14"
rgb = "0.8"
yuv = { version = "0.8", features = ["rayon", "professional_mode"] }
color = "0.3"
colorous = "1.0"
colorutils-rs = "0.7"
palette = "0.7"
image = "0.25"
imageproc = "0.26"
num-traits = "0.2"
anyhow = "1.0"
log = "0.4"
tracing = "0.1"
url = "2.5"
rand = "0.10"
rayon = "1.11"
dashmap = "6.1"
once_cell = "1.21"
num_cpus = "1.17"
ndarray = { version = "0.17", optional = true }
rsmpeg = { git = "https://github.com/larksuite/rsmpeg", default-features = false }

[dev-dependencies]
libc = "0.2"
camino = "1.2"
chrono = "0.4"
ringbuf = "0.4"
ctor = "0.6"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter", "chrono"] }
ab_glyph = "0.2"
libblur = "0.23"
pic-scale = "0.7"
fast_image_resize = "6.0"
histogram_equalization = "0.2"
## security & async
futures = "0.3"
tokio = { version = "1", features = ["full"] }
## sound & audio
cpal = "0.17"
wavers = "1.5"
rubato = "1.0"
dasp = { version = "0.11", features = ["all"] }
rodio = { version = "0.22", features = ["symphonia-all", "tracing"] }

[build-dependencies]
vcpkg = { version = "0.2", optional = true }
pkg-config = { version = "0.3", optional = true }

[package.metadata.docs.rs]
all-features = true

[[example]]
name = "decoding"
path = "examples/decoding.rs"
required-features = ["ndarray"]

[[example]]
name = "encoding"
path = "examples/encoding.rs"
required-features = ["ndarray"]
