[package]
name = "rsmedia"
description = "High-level video toolkit based on ffmpeg."
keywords = ["video", "ffmpeg", "encoding", "decoding", "muxing"]
categories = ["multimedia", "multimedia::video"]
version = "0.9.0"
edition = "2021"
authors = ["Oddity.ai Developers <hello@oddity.ai>"]
repository = "https://github.com/oddity-ai/video-rs"
license = "MIT OR Apache-2.0"
readme = "README.md"

[dependencies]
ffmpeg-next = { path = "./ffmpeg-next" }
ndarray = { version = "0.16", optional = true }
tracing = "0.1"
url = "2"

[dev-dependencies]
image = "0.25"
tokio = { version = "1", features = ["full"] }

[package.metadata.docs.rs]
all-features = true
