edition = "2024"                    # Default: "2015"
style_edition = "2024"
max_width = 120                     # Default: 100
tab_spaces = 4
hard_tabs = false
reorder_imports = true
reorder_modules = true
remove_nested_parens = true
merge_derives = true
force_explicit_abi = true
imports_granularity = "Crate"       # Default: Preserve; consider "Crate" or "Module" as well
imports_layout = "Vertical"         # Default: "Mixed"
newline_style = "Auto"              # Default: "Auto", "Unix"
use_small_heuristics = "Default"
#indent_style = "Visual"            # Default: "Block"
unstable_features = true            # Default: false
## Comments
comment_width = 100                 # Default: 80
wrap_comments = true                # Default: false
normalize_comments = true           # Convert /* */ comments to // comments where possible; default: false
# normalize_doc_attributes = true   # Convert #![doc] and #[doc] attributes to //! and /// doc comments. Default: false
format_code_in_doc_comments = true  # Default: false
## Functions
#fn_params_layout = "Compressed"    # Control the layout of parameters in function signatures. default: "Tall"
## Impl
reorder_impl_items = true           # Reorder impl items. type and const are put first, then macros and methods. Default: false
## Structs
use_field_init_shorthand = true     # Use field initialize shorthand if possible. Default: false
## Macros
use_try_shorthand = true            # Replace uses of the try! macro by the ? shorthand. Default: false
## Ignore specific files
ignore = []