//! Typed sets of FFmpeg flag bits.
//!
//! FFmpeg exposes every "zero or more of these" tunable as a plain integer bit mask: the codec
//! context's `flags` / `flags2` / `thread_type` / `err_recognition`, the scaler context's
//! `flags`, the frame's `flags`, the log flags, the seek flags. The crate models the individual
//! bits of each mask as an enum ([`AVCodecFlag`](crate::AVCodecFlag),
//! [`AVFrameFlag`](crate::AVFrameFlag), [`ScaleQuality`](crate::ScaleQuality),
//! [`ThreadType`](crate::ThreadType), …), but **an enum cannot hold a combination**: a fieldless
//! Rust enum has one variant per value, and `LOW_DELAY | CLOSED_GOP` is not a variant of
//! anything. That is why a *second* type is needed for the set.
//!
//! [`FlagSet<E>`] is that type — a `u32` mask tagged with the enum `E` whose bits it holds.
//! The tag is what buys type safety: `FlagSet<AVCodecFlag>` and `FlagSet<ScaleQuality>` are
//! distinguishable even though both are 32-bit masks, so a codec-flag mask cannot be handed to
//! an API that takes scaler-quality bits. The operations a mask needs are still there: `|` adds
//! bits, `&` intersects, and [`FlagSet::contains`] (generated for each flag enum) tests one bit.
//!
//! # Where a bare `u32` is still wanted
//!
//! Turning a raw mask into a set is deliberately **not** an implicit conversion — there is no
//! `From<u32>` — so a stray integer cannot slip into an API that takes a [`FlagSet`]. That is
//! the whole point: `with_flags(4)` does not compile, while
//! `with_flags(AVCodecFlag::LOW_DELAY)` does. When a raw mask genuinely *is* what you have — a
//! value read back out of an FFmpeg context, or an `AV_*_FLAG_*` constant this crate does not
//! model — say so with [`FlagSet::from_bits`], and read one back out with [`FlagSet::bits`].
//! Bits no variant of `E` names are preserved, so a round trip through FFmpeg is lossless.
//!
//! # Example
//!
//! ```
//! use rsmedia::{AVCodecFlag, FlagSet};
//!
//! // One named flag, or a combination — both are accepted by the same parameter.
//! let one = FlagSet::from(AVCodecFlag::LOW_DELAY);
//! let both = AVCodecFlag::CLOSED_GOP | AVCodecFlag::LOW_DELAY;
//!
//! assert!(both.contains(AVCodecFlag::LOW_DELAY));
//! assert!(!one.contains(AVCodecFlag::CLOSED_GOP));
//! assert!(both.contains(AVCodecFlag::CLOSED_GOP));
//!
//! // `&` keeps the bits two sets agree on.
//! assert!((both & AVCodecFlag::CLOSED_GOP).contains(AVCodecFlag::CLOSED_GOP));
//!
//! // The empty set, an explicit raw mask, and back out again.
//! assert!(FlagSet::<AVCodecFlag>::EMPTY.is_empty());
//! assert_eq!(FlagSet::<AVCodecFlag>::from_bits(0b101).bits(), 0b101);
//! ```

use std::fmt;
use std::hash::{Hash, Hasher};
use std::marker::PhantomData;
use std::ops::{BitAnd, BitAndAssign, BitOr, BitOrAssign};

/// A set of the flag bits modelled by the enum `E`.
///
/// Construct one from named flags (via [`FlagSet::from`] or the `|` operator on `E`) or from a
/// raw mask (via [`FlagSet::from_bits`]); see the [module documentation](self) for the reasoning
/// behind the type.
///
/// The rank of `E` is carried only in [`PhantomData`]: nothing here reads `E`'s variants, which
/// is why the type has no `E: ...` bound. The per-enum conversions
/// (`From<E>`, `contains`, `Into<the FFmpeg repr>`) are generated by `ffi_enum!` alongside each
/// flag table, so they exist for exactly the enums that model a bit set.
pub struct FlagSet<E> {
    /// The raw mask. Stored as `u32` for every table, including the ones whose FFmpeg field is
    /// `int` (the seek flags): the mask width is not what distinguishes flag types here — `E`
    /// is — and FFmpeg's flag values are small positive powers of two in both cases. The
    /// `Into<repr>` conversion generated per table casts back at the FFI boundary.
    bits: u32,
    _flags: PhantomData<E>,
}

impl<E> FlagSet<E> {
    /// No bits set.
    pub const EMPTY: Self = Self {
        bits: 0,
        _flags: PhantomData,
    };

    /// A set holding exactly the bits of `bits`.
    ///
    /// This is the explicit doorway between a raw FFmpeg mask and the typed set, for the cases
    /// where the mask comes from *outside* the crate: a value read back from a context, or a
    /// constant no variant of `E` names. Bits outside `E`'s table are kept as given, which is
    /// what makes reading a mask back out of FFmpeg lossless.
    ///
    /// ```
    /// use rsmedia::{AVCodecFlag, FlagSet};
    ///
    /// // A mask from somewhere else, adopted as-is.
    /// let raw = FlagSet::<AVCodecFlag>::from_bits(0b1_0000);
    /// assert_eq!(raw.bits(), 0b1_0000);
    /// ```
    pub const fn from_bits(bits: u32) -> Self {
        Self {
            bits,
            _flags: PhantomData,
        }
    }

    /// The raw mask, for handing back to FFmpeg or for assembling bits across flag types.
    pub const fn bits(self) -> u32 {
        self.bits
    }

    /// Whether no bit is set.
    ///
    /// The empty set is a real value, not an error: `0` is how "none of these" is written, and
    /// some FFmpeg fields mean that literally (no scaling-quality bits).
    ///
    /// ```
    /// use rsmedia::{AVCodecFlag, FlagSet};
    ///
    /// assert!(FlagSet::<AVCodecFlag>::EMPTY.is_empty());
    /// assert!(!(AVCodecFlag::LOW_DELAY | AVCodecFlag::CLOSED_GOP).is_empty());
    /// ```
    pub const fn is_empty(self) -> bool {
        self.bits == 0
    }

    /// Whether **every** bit of `other` is set — the set form of the per-table
    /// `contains`, which tests a single flag.
    ///
    /// `other` may be a single flag or another set, so a combination is tested
    /// the same way one bit is, without dropping to raw masks:
    ///
    /// ```
    /// use rsmedia::{AVCodecFlag, FlagSet};
    ///
    /// let both = AVCodecFlag::LOW_DELAY | AVCodecFlag::CLOSED_GOP;
    /// let three = both | AVCodecFlag::BITEXACT;
    ///
    /// assert!(three.contains_all(both));
    /// // A single flag is accepted too — `contains`'s job, spelled the same way.
    /// assert!(three.contains_all(AVCodecFlag::BITEXACT));
    /// assert!(!both.contains_all(AVCodecFlag::BITEXACT));
    /// // The empty set is contained by everything, as sets go.
    /// assert!(both.contains_all(FlagSet::EMPTY));
    /// ```
    pub fn contains_all(self, other: impl Into<Self>) -> bool {
        let other = other.into();
        self.bits & other.bits == other.bits
    }

    /// `self` with `flag`'s bits forced on (`on == true`) or off (`on == false`).
    ///
    /// The write-side counterpart of the per-table `contains`: where `contains`
    /// reads one bit, this sets or clears it without disturbing any other bit,
    /// including ones no variant of `E` names. It pairs with
    /// [`from_bits`](Self::from_bits) when a mask read back out of FFmpeg has to
    /// be edited one flag at a time — the case where a caller holds a raw mask
    /// and a set of named overrides.
    ///
    /// ```
    /// use rsmedia::{AVCodecFlag, FlagSet};
    ///
    /// let set = FlagSet::<AVCodecFlag>::EMPTY
    ///     .set(AVCodecFlag::LOW_DELAY, true)
    ///     .set(AVCodecFlag::CLOSED_GOP, true);
    /// assert!(set.contains(AVCodecFlag::LOW_DELAY));
    /// assert!(set.contains(AVCodecFlag::CLOSED_GOP));
    ///
    /// // Forcing one flag off clears only that bit.
    /// let again = set.set(AVCodecFlag::LOW_DELAY, false);
    /// assert!(!again.contains(AVCodecFlag::LOW_DELAY));
    /// assert!(again.contains(AVCodecFlag::CLOSED_GOP));
    /// ```
    pub fn set(mut self, flag: impl Into<Self>, on: bool) -> Self {
        let flag = flag.into();
        self.bits = if on {
            self.bits | flag.bits
        } else {
            self.bits & !flag.bits
        };
        self
    }
}

impl<E> Default for FlagSet<E> {
    /// The empty set.
    fn default() -> Self {
        Self::EMPTY
    }
}

// `Clone` / `Copy` / `PartialEq` / `Eq` / `Hash` / `Debug` are written by hand rather than
// derived: a derive would add an `E: Clone` (etc.) bound, but `E` is never stored — only
// `PhantomData<E>` is — so requiring anything of `E` here would be a bound that is both
// unsatisfiable-in-principle and meaningless.
impl<E> Clone for FlagSet<E> {
    fn clone(&self) -> Self {
        *self
    }
}

impl<E> Copy for FlagSet<E> {}

impl<E> PartialEq for FlagSet<E> {
    fn eq(&self, other: &Self) -> bool {
        self.bits == other.bits
    }
}

impl<E> Eq for FlagSet<E> {}

impl<E> Hash for FlagSet<E> {
    fn hash<H: Hasher>(&self, state: &mut H) {
        self.bits.hash(state);
    }
}

impl<E> fmt::Debug for FlagSet<E> {
    /// Prints the mask in binary, which is how flags are read: `FlagSet(0b101)`.
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "FlagSet({:#b})", self.bits)
    }
}

// Hex formatting is the other conventional way to read a bit mask, and a mask is
// what a `FlagSet` is; `Debug` already picked one base, so rather than making
// every caller go through [`FlagSet::bits`] to get the other, the formatting
// traits are implemented here — `E` is not involved in either.
impl<E> fmt::LowerHex for FlagSet<E> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        fmt::LowerHex::fmt(&self.bits, f)
    }
}

impl<E> fmt::UpperHex for FlagSet<E> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        fmt::UpperHex::fmt(&self.bits, f)
    }
}

/// `set | set`: the union of the two sets' bits.
impl<E> BitOr for FlagSet<E> {
    type Output = Self;

    fn bitor(self, rhs: Self) -> Self::Output {
        Self::from_bits(self.bits | rhs.bits)
    }
}

/// `set |= set`: adds the right-hand bits to the set.
impl<E> BitOrAssign for FlagSet<E> {
    fn bitor_assign(&mut self, rhs: Self) {
        self.bits |= rhs.bits;
    }
}

/// `set & set`: the bits the two sets have in common.
impl<E> BitAnd for FlagSet<E> {
    type Output = Self;

    fn bitand(self, rhs: Self) -> Self::Output {
        Self::from_bits(self.bits & rhs.bits)
    }
}

/// `set &= set`: keeps only the bits both sets have.
impl<E> BitAndAssign for FlagSet<E> {
    fn bitand_assign(&mut self, rhs: Self) {
        self.bits &= rhs.bits;
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::codec::{AVCodecFlag, ThreadType};
    use crate::scale::ScaleQuality;

    /// The operators on the set itself, and the raw doorway — exercised through the generated
    /// per-table impls, so this doubles as a check that `ffi_enum!` wires them up.
    #[test]
    fn test_flag_set_operations() {
        // A single flag converts into a set; a combination is built with `|`.
        let one: FlagSet<AVCodecFlag> = AVCodecFlag::LOW_DELAY.into();
        assert_eq!(one.bits(), AVCodecFlag::LOW_DELAY.as_raw());
        assert!(one.contains(AVCodecFlag::LOW_DELAY));

        let both = AVCodecFlag::CLOSED_GOP | AVCodecFlag::LOW_DELAY;
        assert_eq!(
            both.bits(),
            AVCodecFlag::CLOSED_GOP.as_raw() | AVCodecFlag::LOW_DELAY.as_raw()
        );

        // A chain keeps working: `Enum | Enum` yields a set, and `set | Enum` continues it.
        let three = AVCodecFlag::CLOSED_GOP | AVCodecFlag::LOW_DELAY | AVCodecFlag::BITEXACT;
        assert_eq!(three, both | AVCodecFlag::BITEXACT);
        // ...and so does the mirror image, `Enum | set`.
        assert_eq!(three, AVCodecFlag::BITEXACT | both);

        // `&` intersects; `contains` reads a single bit.
        assert!(three.contains(AVCodecFlag::BITEXACT));
        assert!(both.contains(AVCodecFlag::CLOSED_GOP));
        assert!(!both.contains(AVCodecFlag::BITEXACT));
        assert!((three & both) == both);
        assert!((both & AVCodecFlag::BITEXACT).is_empty());

        // Assign forms.
        let mut acc = FlagSet::EMPTY;
        acc |= AVCodecFlag::LOW_DELAY;
        acc |= AVCodecFlag::CLOSED_GOP;
        assert_eq!(acc, both);
        acc &= AVCodecFlag::LOW_DELAY;
        assert_eq!(acc, one);
    }

    /// The empty set is expressible and is distinct from "unset": `0` is a real value some
    /// FFmpeg fields accept (`SwsContext.flags` with no quality bits).
    #[test]
    fn test_flag_set_empty_and_default() {
        assert!(FlagSet::<AVCodecFlag>::EMPTY.is_empty());
        assert_eq!(FlagSet::<AVCodecFlag>::default(), FlagSet::EMPTY);
        assert_eq!(FlagSet::<ScaleQuality>::from_bits(0), FlagSet::EMPTY);
        assert!(!(ThreadType::FRAME | ThreadType::SLICE).is_empty());
    }

    /// A raw mask is adopted verbatim, **including bits no variant names** — that is what makes
    /// reading a mask back out of FFmpeg lossless.
    #[test]
    fn test_flag_set_from_bits_keeps_unknown_bits() {
        // Pick a bit that is above every modelled AV_CODEC_FLAG_* value.
        let unknown = 1u32 << 30;
        let set = FlagSet::<AVCodecFlag>::from_bits(unknown | AVCodecFlag::LOW_DELAY.as_raw());
        assert_eq!(set.bits(), unknown | AVCodecFlag::LOW_DELAY.as_raw());
        assert!(set.contains(AVCodecFlag::LOW_DELAY));
        assert!(!set.is_empty());
    }

    /// Sets of different flag types are distinct types even though both are 32-bit masks.
    /// (The negative half — passing one where the other is wanted — is a compile error and thus
    /// cannot be asserted here; this pins the positive statement that the tag survives.)
    #[test]
    fn test_flag_set_is_tagged_by_its_flag_enum() {
        let codec: FlagSet<AVCodecFlag> = AVCodecFlag::LOW_DELAY.into();
        let thread: FlagSet<ThreadType> = ThreadType::FRAME.into();
        assert_eq!(codec.bits(), AVCodecFlag::LOW_DELAY.as_raw());
        assert_eq!(thread.bits(), ThreadType::FRAME.as_raw());
    }

    /// `Debug` shows the mask, deduplicated from `E`'s own formatting.
    #[test]
    fn test_flag_set_debug_is_binary() {
        let set = AVCodecFlag::LOW_DELAY | AVCodecFlag::CLOSED_GOP;
        assert_eq!(
            format!("{set:?}"),
            format!("FlagSet({:#b})", set.bits()),
            "the mask should print in binary"
        );
    }
}
