name: ci

on:
  push:
    branches: [ "main", "rsmpeg", "dev" ]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [ "main", "rsmpeg", "dev" ]
    paths-ignore:
      - 'README.md'

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  RUST_LOG: "debug"
  RUST_BACKTRACE: 1
  RUSTFLAGS: "-D warnings"

jobs:

  build-linux:
    name: build / ${{ matrix.platform }} / ffmpeg-${{ matrix.ffmpeg_version }}
    runs-on: ubuntu-latest
    container:
      image: jrottenberg/ffmpeg:${{ matrix.ffmpeg_version }}-ubuntu

    env:
      DOCKER_DEFAULT_PLATFORM: ${{ matrix.platform }}

    strategy:
      fail-fast: false
      matrix:
        platform: ["linux/amd64", "linux/arm64"]
        ffmpeg_version: ["6.1", "7.1"]
        include:
          - ffmpeg_version: "6.1"
            feature: "ndarray,ffmpeg6,link_system_ffmpeg"
          - ffmpeg_version: "7.1"
            feature: "ndarray,ffmpeg7,link_system_ffmpeg"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          DEBIAN_FRONTEND=noninteractive apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y \
            build-essential \
            ca-certificates \
            clang \
            lld \
            nasm \
            yasm \
            curl \
            wget \
            gnupg \
            libc6 \
            libc6-dev \
            libgcc-s1 \
            linux-libc-dev \
            binutils \
            pkg-config \
            libx264-dev \
            libx265-dev \
            libavcodec-dev \
            libavformat-dev \
            libavutil-dev \
            libswscale-dev \
            libswresample-dev \
            libavdevice-dev \
            libavfilter-dev \
            libssl-dev \
            librtmp-dev \
            libvpx-dev \
            libaom-dev \
            libsvtav1-dev \
            libxvidcore-dev \
            libmp3lame-dev \
            libopus-dev \
            libvorbis-dev \
            libfdk-aac-dev \
            libasound2-dev

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt, clippy, rust-src, llvm-tools-preview, rust-analysis

      - name: Clippy check
        run: cargo clippy --no-default-features --features ${{ matrix.feature }} -- -D warnings

      - name: Build
        run: cargo build --no-default-features --features ${{ matrix.feature }} --verbose

      - name: Run Test
        run: cargo test --all --no-default-features --features ${{ matrix.feature }} --verbose -- --nocapture

  build-macos:
    name: build / macos / latest ffmpeg
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install dependencies
        run: |
          brew install ffmpeg pkg-config

      - name: Clippy check
        run: cargo clippy --all --all-features -- -D warnings

      - name: Build
        run: cargo build --all --all-features --verbose

      - name: Run Test
        run: cargo test --all --all-features --verbose -- --nocapture

  build-windows:
    name: build / windows-${{ matrix.config.vcpkg_triplet }} / ffmpeg-7.1
    runs-on: windows-latest

    env:
      FFMPEG_VERSION: "7.1"
      BUILD_FEATURES: "ndarray,ffmpeg7,link_vcpkg_ffmpeg"

    strategy:
      matrix:
        config:
          - target: "x86_64-pc-windows-msvc"
            vcpkg_triplet: "x64-windows-static"
            rustflags: "-Ctarget-feature=+crt-static"
          - target: "x86_64-pc-windows-msvc"
            vcpkg_triplet: "x64-windows-static-md"
          - target: "x86_64-pc-windows-msvc"
            vcpkg_triplet: "x64-windows"
            dynamic: true
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt, clippy
          targets: ${{ matrix.config.target }}

      # Using this since it's used by clang-sys's CI
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "10.0"
          directory: ${{ github.workspace }}/clang

      - name: Cache vcpkg
        id: cache
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/vcpkg
          key: vcpkg-${{ runner.os }}-${{ matrix.config.vcpkg_triplet }}

      - name: Build vcpkg
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/microsoft/vcpkg --depth 1
          ./vcpkg/bootstrap-vcpkg.bat

      - name: Install Dependencies
        run: |
          ./vcpkg/vcpkg.exe install ffmpeg:${{ matrix.config.vcpkg_triplet }}

      - name: Set env
        shell: bash
        run: |
          if [ '${{ matrix.config.dynamic }}' != '' ]; then
            echo "VCPKGRS_DYNAMIC=1" >> $GITHUB_ENV
          fi

      - name: Clippy check
        shell: bash
        env:
          RUSTFLAGS: ${{ matrix.config.rustflags }}
          VCPKG_ROOT: ${{ github.workspace }}/vcpkg
          VCPKG_DEFAULT_TRIPLET: ${{ matrix.config.vcpkg_triplet }}
          LIBCLANG_PATH: ${{ github.workspace }}/clang/lib
          LLVM_CONFIG_PATH: ${{ github.workspace }}/clang/bin/llvm-config
        run: cargo clippy --no-default-features --features ${{ env.BUILD_FEATURES }} --target ${{ matrix.config.target }} -- -D warnings

      - name: Build
        shell: bash
        env:
          RUSTFLAGS: ${{ matrix.config.rustflags }}
          VCPKG_ROOT: ${{ github.workspace }}/vcpkg
          VCPKG_DEFAULT_TRIPLET: ${{ matrix.config.vcpkg_triplet }}
          LIBCLANG_PATH: ${{ github.workspace }}/clang/lib
          LLVM_CONFIG_PATH: ${{ github.workspace }}/clang/bin/llvm-config
        run: cargo build --no-default-features --features ${{ env.BUILD_FEATURES }} --target ${{ matrix.config.target }} --verbose

      - name: Run Test
        shell: bash
        env:
          RUSTFLAGS: ${{ matrix.config.rustflags }}
          VCPKG_ROOT: ${{ github.workspace }}/vcpkg
          VCPKG_DEFAULT_TRIPLET: ${{ matrix.config.vcpkg_triplet }}
          LIBCLANG_PATH: ${{ github.workspace }}/clang/lib
          LLVM_CONFIG_PATH: ${{ github.workspace }}/clang/bin/llvm-config
        run: cargo test --no-default-features --features ${{ env.BUILD_FEATURES }} --target ${{ matrix.config.target }} --verbose -- --nocapture

  test_and_clippy:
    name: Clippy & Test / ${{ matrix.platform }} / ffmpeg-${{ matrix.ffmpeg_version }}
    runs-on: ubuntu-latest
    container:
      image: jrottenberg/ffmpeg:${{ matrix.ffmpeg_version }}-ubuntu

    env:
      DOCKER_DEFAULT_PLATFORM: ${{ matrix.platform }}

    strategy:
      fail-fast: false
      matrix:
        platform: ["linux/amd64", "linux/arm64"]
        ffmpeg_version: ["6.1", "7.1"]
        include:
          - ffmpeg_version: "6.1"
            feature: "ndarray,ffmpeg6,link_system_ffmpeg"
          - ffmpeg_version: "7.1"
            feature: "ndarray,ffmpeg7,link_system_ffmpeg"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          DEBIAN_FRONTEND=noninteractive apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y \
            build-essential \
            ca-certificates \
            clang \
            lld \
            nasm \
            yasm \
            curl \
            wget \
            gnupg \
            libc6 \
            libc6-dev \
            libgcc-s1 \
            linux-libc-dev \
            binutils \
            pkg-config \
            libx264-dev \
            libx265-dev \
            libavcodec-dev \
            libavformat-dev \
            libavutil-dev \
            libswscale-dev \
            libswresample-dev \
            libavdevice-dev \
            libavfilter-dev \
            libssl-dev \
            librtmp-dev \
            libvpx-dev \
            libaom-dev \
            libsvtav1-dev \
            libxvidcore-dev \
            libmp3lame-dev \
            libopus-dev \
            libvorbis-dev \
            libfdk-aac-dev \
            libasound2-dev

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Clippy
        run: cargo clippy --all --no-default-features --features ${{ matrix.feature }} -- -D warnings

      - name: Test
        run: cargo test --all --no-default-features --features ${{ matrix.feature }} --verbose -- --nocapture

  lints:
    name: Rust fmt / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt

      - name: Rust fmt
        run: cargo fmt --all -- --check
